services:
  - type: web
    name: construccionfinal
    runtime: python
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn run:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: NODE_VERSION
        value: "20.11.0"
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
